export const AUTH_ACCESS_TOKEN_SECRET = '__AUTH_AT_SECRET__';
export const AUTH_REFRESH_TOKEN_SECRET = '__AUTH_RT_SECRET__';
export const AUTH_ACCESS_TOKEN_EXPIRATION = '15m'; // 10s, 15m, 2h
export const AUTH_REFRESH_TOKEN_EXPIRATION = '2h';
