# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy UI on Github Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'code/frontend/**'
      - '.github/workflows/build-ui-ghpages.yml'
#  pull_request:
#    branches: ["main"]
  workflow_dispatch:

#Could be main config
#env:
#  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

env:
  node-version: 20

jobs:
  build:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }} #${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: code/frontend/home-expenses-ui/package-lock.json
          node-version: ${{ env.node-version }}
#          node-version: ${{ matrix.node-version }}

      - name: "CI"
        run: |
          cd code/frontend/home-expenses-ui
          npm ci

      - name: Prepare app version
        id: appVersionId
        run: |
          BUILDNUMBER=$(date +"%Y%m%d").${GITHUB_RUN_NUMBER}
          echo build-number=$BUILDNUMBER >> $GITHUB_OUTPUT
        shell: bash

      - name: Populate config.json
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["code/frontend/gh_deployment/dev/assets/config/*.json"]'
        env:
          APP_VERSION: ${{ steps.appVersionId.outputs.build-number }}

      - name: "Build"
        run: |
          cd code/frontend/home-expenses-ui
          npm run build --if-present

      - name: "Add config.json"
        run: |
          mkdir -p code/frontend/home-expenses-ui/dist/assets/config 
          cat code/frontend/gh_deployment/dev/assets/config/config.json > code/frontend/home-expenses-ui/dist/assets/config/config.json

      - name: Print all files
        run: |
          find .

      - name: "Test"
        run: |
          cd code/frontend/home-expenses-ui
          npm test

      - name: "Lint"
        run: |
          cd code/frontend/home-expenses-ui
          npm run lint

      - name: "Deploy to Github Pages"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd code/frontend/home-expenses-ui
          npm run deploy
