# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Deploy UI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: code/frontend/home-expenses-ui/package-lock.json

      - name: "npm CI and Build"
        run: |
          cd code/frontend/home-expenses-ui
          npm ci
          npm run build --if-present

      - name: "Testing"
        run: |
          cd code/frontend/home-expenses-ui
          npm test

      - name: "Lint"
        run: |
          cd code/frontend/home-expenses-ui
          npm run lint
