# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure Key Vault Testing

on:
  push:
    paths:
      - '.github/workflows/get-key-vault-secret.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
#    environment: PROD

    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: '57ae7e22-49e6-4799-84c6-07232102806a'
          tenant-id: 'b41b72d0-4e9f-4c26-8a69-f949f367c91d'
          subscription-id: '4d2f3ad4-f78e-483b-a384-018d838538cb'
#          allow-no-subscriptions: true

#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
#          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}



#      - name: 'Run az commands'
#        run: |
#          az account show
#          az group list
#          pwd

      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd

      - name: Azure CLI script - get secret from KeyVault
        id: step_one
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo myVar=$(az keyvault secret show --vault-name he-keyvault --name vova-test --query value) >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.myVar }}"
