name: Test CRON Scheduler

on:

  #Run every day at 09:00 UTC

  schedule:
    - cron: 0 9 * * *

  workflow_dispatch:

jobs:
  my_task:
    name: Check scheduler
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo "Run tick"
        shell: bash
